<?php

use Snowdog\Academy\Controller\Account;
use Snowdog\Academy\Model\UserCryptocurrency;

/** @var $this Account */

require_once(__DIR__ . '/../common/header.phtml'); ?>

<div class="container">
    <section id="your-funds" class="padded">
        <h3>Your funds: <?= $this->getUser()->getFunds() ?> USD
        <a href="/funds">Add Funds</a>
        </h3>
    </section>
    <section id="cryptos-list" class="padded">
        <h3>Your cryptocurrencies</h3>
        <?php if (count($this->getUserCryptocurrencies())==0): ?>
        (empty, no currencies)    
        <?php else: ?>
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Name</th>
                <th>Amount</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->getUserCryptocurrencies() as $currency): /** @var UserCryptocurrency $currency */?>
                <tr>
                    <td><?= $currency->getName()?></td>
                    <td><?= $currency->getAmount()?></td>
                    <td><a href="/cryptos/sell/<?= $currency->getId() ?>">Sell</a></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <?php endif; ?>
    </section>
</div>

<?php require_once(__DIR__ . '/../common/footer.phtml'); ?>
