<?php

require_once(__DIR__ . '/../common/header.phtml'); ?>

<div class="container">
    <script>
    function onSubmitCheck(){
        let buy_amount=parseInt(amount.value)
        let price=<?= $cryptocurrency->getPrice() ?>;
        let funds=<?= $user->getFunds() ?>;
        let payment=buy_amount*price
        let allowed=payment<=funds
        if(!allowed) alert("not allowed: not enough funds! funds:"+funds+" payment:"+payment)
        return allowed
    }
    </script>
    <section id="buy-form" class="padded">
        <h3>Buy <?= $cryptocurrency->getName() ?> (<?= $cryptocurrency->getSymbol() ?>) Price: <?= $cryptocurrency->getPrice() ?> USD</h3>
        <form method="post" action="/cryptos/buy/<?= $cryptocurrency->getId() ?>"
        onsubmit="return onSubmitCheck()"
        >
            <div class="form-group">
                <!-- <input type="text" class="form-control" id="amount" placeholder="Amount" name="amount"> -->

                <!-- non-negative integer amount -->
                <input
                name="amount" id="amount"
                class="form-control" placeholder="Amount"
                type="number" min="0" oninput="validity.valid||(value='')"
                >

            </div>
            <button type="submit" class="btn btn-success">Buy</button>
        </form>
    </section>
</div>

<?php require_once(__DIR__ . '/../common/footer.phtml'); ?>
