<?php

require_once(__DIR__ . '/../common/header.phtml'); ?>

<div class="container">
    <section id="sell-form" class="padded">
        <h3>Sell <?= $this->cryptocurrency->getName() ?> (<?= $this->cryptocurrency->getSymbol() ?>)</h3>
        <form method="post" action="/cryptos/sell/<?= $this->cryptocurrency->getId() ?>">
            <div class="form-group">
                <!-- <input type="text" class="form-control" id="amount" placeholder="Amount" name="amount"> -->

                <!-- non-negative integer amount -->
                <input
                name="amount" id="amount"
                class="form-control" placeholder="Amount"
                type="number" min="0" oninput="validity.valid||(value='')"
                >

            </div>
            <button type="submit" class="btn btn-success">Sell</button>
        </form>
    </section>
</div>

<?php require_once(__DIR__ . '/../common/footer.phtml'); ?>
